export enum FilterType {
  BASE = 'BASE',
  COLLABORATIVE = 'COLLABORATIVE',
  CONTENT_BASED = 'CONTENT_BASED',
  HYBRID = 'HYBRID',
  KNOWLEDGE_BASED = 'KNOWLEDGE_BASED',
  PROCESS_AWARE = 'PROCESS_AWARE',
}
