export enum RecommendationServiceModelType {
  BASE = 'BASE',
  KNOWLEDGE_BASED =  'KNOWLEDGE_BASED',
  CONTENT_BASED =  'CONTENT_BASED',
  COLLABORATIVE =  'COLLABORATIVE',
  PROCESS_AWARE =  'PROCESS_AWARE',
  HYBRID =  'HYBRID',
}
